export const Texts = {
  appName: 'CartPay',
  tabs: {
    cart: 'Sepet',
    produce: 'Meyve-Sebze',
    receipts: 'Fişlerim',
  },
  cart: {
    title: 'Alışveriş Sepeti',
    empty: 'Sepetiniz boş',
    emptyDesc: 'Ürün eklemek için barkod okutun',
    scanButton: 'Barkod Okut',
    total: 'Toplam',
    itemCount: 'Ürün',
    proceedToPayment: 'Ödemeye Geç',
  },
  scanner: {
    title: 'Barkod Okut',
    instruction: 'Barkodu kare içine hizalayın',
    productAdded: 'Ürün sepete eklendi',
    productNotFound: 'Ürün bulunamadı',
  },
  produce: {
    title: 'Meyve & Sebze',
    weightBased: 'Tartılarak',
    unitBased: 'Adet',
    enterWeight: 'Gram girin',
    selectQuantity: 'Adet seçin',
    addToCart: 'Sepete Ekle',
    perKg: '/ kg',
    perUnit: '/ adet',
  },
  payment: {
    title: 'Ödeme',
    summary: 'Sipariş Özeti',
    total: 'Toplam Tutar',
    nfcPrompt: 'Kartınızı okutun',
    simulateButton: 'Ödemeyi Simüle Et',
    processing: 'İşleniyor...',
    success: 'Ödeme Başarılı!',
    nfcNotSupported: 'NFC desteklenmiyor',
  },
  receipt: {
    title: 'Fiş Detayı',
    receiptId: 'Fiş No',
    date: 'Tarih',
    time: 'Saat',
    items: 'Ürünler',
    paymentMethod: 'Ödeme',
    nfcPayment: 'NFC Kartı',
    simulatedPayment: 'Simüle Edildi',
    downloadPdf: 'PDF İndir',
    share: 'Paylaş',
    delete: 'Sil',
    thanksMessage: 'Bizi tercih ettiğiniz için teşekkürler!',
    ecoNote: 'Bu fiş kağıtsız olarak kaydedilmiştir.',
  },
  receipts: {
    title: 'Fişlerim',
    empty: 'Henüz fiş bulunmuyor',
    emptyDesc: 'Alışveriş yaptığınızda fişler burada görünecek',
  },
  common: {
    cancel: 'İptal',
    confirm: 'Onayla',
    close: 'Kapat',
    back: 'Geri',
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    tl: '₺',
    quantity: 'Adet',
    unit: 'Birim',
    price: 'Fiyat',
    subtotal: 'Ara Toplam',
    gram: 'gr',
  },
};
